#MOTOR
DKIRI_LPWM_PIN='d:11:p' # digital pin 10 as PWM
DKIRI_RPWM_PIN='d:10:p' 
DKIRI_LEN_PIN='d:35:o' 
DKIRI_REN_PIN='d:37:o' 

BKIRI_LPWM_PIN='d:8:p'
BKIRI_RPWM_PIN='d:9:p' 
BKIRI_LEN_PIN='d:31:o' 
BKIRI_REN_PIN='d:33:o' 

DKANAN_LPWM_PIN='d:7:p'
DKANAN_RPWM_PIN='d:6:p' 
DKANAN_LEN_PIN='d:27:o' 
DKANAN_REN_PIN='d:29:o' 

BKANAN_LPWM_PIN='d:4:p'
BKANAN_RPWM_PIN='d:5:p' 
BKANAN_LEN_PIN='d:23:o' 
BKANAN_REN_PIN='d:25:o'
